#! /bin/bash

#PBS -l nodes=1:ppn=20
#PBS -l walltime=12:00:00
#PBS -q workq
#PBS -j oe
#PBS -M yding8@lsu.edu
##PBS -m ae

date

# Things that should be customized, carefully of course.

WORKDIR=/work/jaydy/working/SingleConfDock2

FILES=/work/jaydy/dat/astex/total_lst

TASK=${WORKDIR}/geaux.bash

for complex in `cat $FILES`
do
    echo $complex
    stdout=${WORKDIR}/${complex}.out
    bash $TASK $complex > $stdout
    echo $complex 'done'
done

date
